// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    HomeStoreCardHorizontal: typeof import('./components/HomeStoreCardHorizontal.vue')['default']
    HomeStoreCardVertical: typeof import('./components/HomeStoreCardVertical.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stars: typeof import('./components/Stars.vue')['default']
    StoreCard: typeof import('./components/StoreCard.vue')['default']
    StoreCardHorizontal: typeof import('./components/StoreCardHorizontal.vue')['default']
    StoreCardVertical: typeof import('./components/StoreCardVertical.vue')['default']
    Tabbar: typeof import('./components/Tabbar.vue')['default']
  }
}
