// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DirectNotification
 */
export interface DirectNotification {
    /**
     * 
     * @type {string}
     * @memberof DirectNotification
     */
    target: string;
    /**
     * 
     * @type {string}
     * @memberof DirectNotification
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DirectNotification
     */
    message: string;
}


