// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2013
 */
export interface InlineResponse2013 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse2013
   */
  seatTypeId: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2013
   */
  queueId: number;
}
