// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse2003Resources } from './inline-response2003-resources';
import { InlineResponse2005QueuesInfo } from './inline-response2005-queues-info';

/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005
     */
    merchantId: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005
     */
    name: string;
    /**
     * StoreType
     * @type {string}
     * @memberof InlineResponse2005
     */
    type: InlineResponse2005TypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse2005
     */
    phoneNumbers: Array<string>;
    /**
     * Store Status
     * @type {string}
     * @memberof InlineResponse2005
     */
    status: InlineResponse2005StatusEnum;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005
     */
    registerTime: number;
    /**
     * 
     * @type {InlineResponse2003Resources}
     * @memberof InlineResponse2005
     */
    resources: InlineResponse2003Resources;
    /**
     * 
     * @type {Array<InlineResponse2005QueuesInfo>}
     * @memberof InlineResponse2005
     */
    queuesInfo: Array<InlineResponse2005QueuesInfo>;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse2005TypeEnum {
    Restaurant = 'Restaurant',
    Cafe = 'Cafe'
}
/**
    * @export
    * @enum {string}
    */
export enum InlineResponse2005StatusEnum {
    OnService = 'onService',
    StopService = 'stopService'
}



