// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
    /**
     * 
     * @type {number}
     * @memberof InlineObject3
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject3
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject3
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject3
     */
    userType: InlineObject3UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineObject3
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject3
     */
    status?: InlineObject3StatusEnum;
    /**
     * timestamp
     * @type {number}
     * @memberof InlineObject3
     */
    createTime?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineObject3UserTypeEnum {
    Customer = 'customer',
    Merchant = 'merchant'
}
/**
    * @export
    * @enum {string}
    */
export enum InlineObject3StatusEnum {
    Active = 'active',
    Cancelled = 'cancelled'
}



