// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {number}
     * @memberof InlineObject1
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    userType: InlineObject1UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject1
     */
    status?: InlineObject1StatusEnum;
    /**
     * timestamp
     * @type {number}
     * @memberof InlineObject1
     */
    createTime?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineObject1UserTypeEnum {
    Customer = 'customer',
    Merchant = 'merchant'
}
/**
    * @export
    * @enum {string}
    */
export enum InlineObject1StatusEnum {
    Active = 'active',
    Cancelled = 'cancelled'
}



