// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SeatType } from './seat-type';

/**
 * 
 * @export
 * @interface InlineResponse2012
 */
export interface InlineResponse2012 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    storeId: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    customerId: number;
    /**
     * 
     * @type {SeatType}
     * @memberof InlineResponse2012
     */
    seatType: SeatType;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    queueNumber: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    queueId: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    startTime: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2012
     */
    endTime: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2012
     */
    status: InlineResponse2012StatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse2012StatusEnum {
    Pending = 'pending',
    Seated = 'seated',
    Skipped = 'skipped'
}



