// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse2001
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2001
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2001
   */
  password?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2001
   */
  userType?: InlineResponse2001UserTypeEnum;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2001
   */
  phoneNumber?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2001
   */
  status?: InlineResponse2001StatusEnum;
  /**
   * timestamp
   * @type {number}
   * @memberof InlineResponse2001
   */
  createTime?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum InlineResponse2001UserTypeEnum {
  Customer = "customer",
  Merchant = "merchant",
}
/**
 * @export
 * @enum {string}
 */
export enum InlineResponse2001StatusEnum {
  Active = "active",
  Cancelled = "cancelled",
}
