// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    userType: InlineResponse200UserTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    status: InlineResponse200StatusEnum;
    /**
     * timestamp
     * @type {number}
     * @memberof InlineResponse200
     */
    createTime?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse200UserTypeEnum {
    Customer = 'customer',
    Merchant = 'merchant'
}
/**
    * @export
    * @enum {string}
    */
export enum InlineResponse200StatusEnum {
    Active = 'active',
    Cancelled = 'cancelled'
}



