// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SeatType } from './seat-type';
import { StoresResources } from './stores-resources';

/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {number}
     * @memberof InlineObject4
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject4
     */
    merchantId: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    name: string;
    /**
     * StoreType
     * @type {string}
     * @memberof InlineObject4
     */
    type: InlineObject4TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    address: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject4
     */
    phoneNumbers: Array<string>;
    /**
     * queue ids
     * @type {Array<SeatType>}
     * @memberof InlineObject4
     */
    seatTypes: Array<SeatType>;
    /**
     * Store Status
     * @type {string}
     * @memberof InlineObject4
     */
    status?: InlineObject4StatusEnum;
    /**
     * 
     * @type {StoresResources}
     * @memberof InlineObject4
     */
    resources: StoresResources;
    /**
     * 
     * @type {number}
     * @memberof InlineObject4
     */
    registerTime?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineObject4TypeEnum {
    Restaurant = 'Restaurant',
    Cafe = 'Cafe'
}
/**
    * @export
    * @enum {string}
    */
export enum InlineObject4StatusEnum {
    OnService = 'onService',
    StopService = 'stopService'
}



