// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2004QueuesInfo
 */
export interface InlineResponse2004QueuesInfo {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2004QueuesInfo
     */
    queueId: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2004QueuesInfo
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004QueuesInfo
     */
    seatTypeName: string;
}


