// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    storeId: number;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    type: ReportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    createdTime: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ReportTypeEnum {
    AverageWaitTime = 'averageWaitTime'
}



