// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    storeId: number;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    type: ReportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    createdTime: number;
    /**
     * time unit of report
     * @type {string}
     * @memberof Report
     */
    unit: ReportUnitEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReportTypeEnum {
    AWT = 'AWT',
    WCNADN = 'WCN_ADN'
}
/**
    * @export
    * @enum {string}
    */
export enum ReportUnitEnum {
    Day = 'day',
    Week = 'week',
    Month = 'month',
    Year = 'year'
}



