// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StoresResources
 */
export interface StoresResources {
  /**
   *
   * @type {string}
   * @memberof StoresResources
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof StoresResources
   */
  imageUrl: string;
  /**
   *
   * @type {number}
   * @memberof StoresResources
   */
  ratings: number;
}
