// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse2003Resources } from './inline-response2003-resources';
import { SeatType } from './seat-type';

/**
 * 
 * @export
 * @interface Store
 */
export interface Store {
    /**
     * 
     * @type {number}
     * @memberof Store
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Store
     */
    merchantId: number;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    name: string;
    /**
     * StoreType
     * @type {string}
     * @memberof Store
     */
    type: StoreTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Store
     */
    address: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Store
     */
    phoneNumbers: Array<string>;
    /**
     * Store Status
     * @type {string}
     * @memberof Store
     */
    status: StoreStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Store
     */
    registerTime: number;
    /**
     * queue ids
     * @type {Array<SeatType>}
     * @memberof Store
     */
    seatTypes: Array<SeatType>;
    /**
     * 
     * @type {InlineResponse2003Resources}
     * @memberof Store
     */
    resources: InlineResponse2003Resources;
}

/**
    * @export
    * @enum {string}
    */
export enum StoreTypeEnum {
    Restaurant = 'Restaurant',
    Cafe = 'Cafe'
}
/**
    * @export
    * @enum {string}
    */
export enum StoreStatusEnum {
    OnService = 'onService',
    StopService = 'stopService'
}



