// tslint:disable
/**
 * iQueue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  userType: UserUserTypeEnum;
  /**
   *
   * @type {string}
   * @memberof User
   */
  phoneNumber: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  status: UserStatusEnum;
  /**
   * timestamp
   * @type {number}
   * @memberof User
   */
  createTime: number;
}

/**
 * @export
 * @enum {string}
 */
export enum UserUserTypeEnum {
  Customer = "customer",
  Merchant = "merchant",
}
/**
 * @export
 * @enum {string}
 */
export enum UserStatusEnum {
  Active = "active",
  Cancelled = "cancelled",
}
