# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: asia-southeast1
  GKE_CLUSTER: ique-app    # TODO: update to cluster name
  GKE_ZONE: asia-southeast1-a  
  DEPLOYMENT_NAME: ique-app # TODO: update to deployment name
  REPOSITORY: ique-star6ucks
  IMAGE: ique-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: Install node.js
        uses: actions/setup-node@master
      
      - name: Installing pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false
          
      - name: Install dependencies
        run: pnpm install
  
      - name: 'Create env file'
        run: |
          touch .env
          echo VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
          echo VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
          echo VITE_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> .env
          echo VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
          echo VITE_FIREBASE_MESSAGING_SENDERID=${{ secrets.FIREBASE_MESSAGING_SENDERID }} >> .env
          echo VITE_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
          echo VITE_VAPID_KEY=${{ secrets.VAPID_KEY }} >> .env
          echo VITE_ONESINGAL_APP_ID=${{ secrets.ONESINGAL_APP_ID }} >> .env
          echo VITE_HASH_SALT=${{ secrets.VITE_HASH_SALT }} >> .env
          cat .env
        
      - name: Building the project
        run: pnpm run build
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist'
          destination: 'ique-app-prod'
          parent: false

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'disable-index-cache'
        run: 'gsutil setmeta -h "Cache-Control: no-cache, no-store, must-revalidate" gs://ique-app-prod/index.html'

      - id: 'redeploy-vercel'
        run: 'curl https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_DEPLOY_PATH }}'

